# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Gradle Build - Spring

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' , '21' ]
        spring: [ '6.0.23' , '6.1.17' , '6.2.3' ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build with Gradle - Spring Framework ${{ matrix.spring }}
        run: ./gradlew build test -Pspring.version=${{ matrix.spring }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: microsphere-projects/microsphere-alibaba-druid